@baseUrl = http://localhost:8000

# @name uuid
GET {{baseUrl}}/utils/uuid

### Service: Register (Create user)
# Send the uuid request above first to generate a unique email address
@email = {{uuid.response.body.$}}
POST {{baseUrl}}/apps/fhp/register
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "email": "{{email}}@example.com",
  "password": "{{$dotenv ADMIN_PASSWORD}}"
}

### Service: Login (Authentication)
POST {{baseUrl}}/apps/fhp/login
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "email": "tec3org@gmail.com",
  "password": "{{$dotenv ADMIN_PASSWORD}}"

}