@baseUrl = http://localhost:8000

### Login as USER (Authentication)
POST {{baseUrl}}/apps/demo/login
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "email": "{{$dotenv ADMIN_EMAIL}}",
  "password": "{{$dotenv ADMIN_PASSWORD}}"
}

##### All of the following require Login above once first

### Service: Logout (Destroy session)
POST {{baseUrl}}/apps/demo/logout
Authorization: Bearer {{$dotenv API_KEY}}

### Service: Find user
GET {{baseUrl}}/apps/demo/users/demo
Authorization: Bearer {{$dotenv API_KEY}}

### Service: Edit user
PATCH {{baseUrl}}/apps/demo/users/tec3
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "username": "masterchiefsensei"
}

### Service: Delete user
DELETE {{baseUrl}}/apps/demo/users/demo
Authorization: Bearer {{$dotenv API_KEY}}
