@baseUrl = http://localhost:8000

### Service: Register (Create user)
POST {{baseUrl}}/apps/promptwiz/register
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "email": "adfgasghghgyfdodddffdfsdfsa@gmail.com",
  "password": "{{$dotenv ADMIN_PASSWORD}}"
}

### Service: Login (Authentication)
POST {{baseUrl}}/apps/promptwiz/login
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "email": "tec3org@gmail.com",
  "password": "{{$dotenv ADMIN_PASSWORD}}"
}
