@baseUrl = http://localhost:8000

##### The following endpoints require an Admin Login first to any app (above)
##### One Login is enough to test all endpoints

### Health Check
POST {{baseUrl}}/gpteams
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "challenge": "OK"
}

### Prompt ChatGPT (gpt-3.5-turbo)
POST {{baseUrl}}/gpteams
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "event": {
    "text": "What is love?",
    "user": "{{$dotenv SLACK_GPTEAMS_DIO_ID}}",
    "thread_ts": "null"
  },
  "authorizations": {
    "is_bot": true
  }
}

### Danger Zone ###
##### Do not execute these endpoints unless you know what you are doing

### Set Home Page (All Users)
POST https://slack.com/api/views.publish
Authorization: Bearer {{$dotenv SLACK_GPTEAMS_DM_TOKEN}}
Content-Type: application/json

{
  "user_id": "{{$dotenv SLACK_GPTEAMS_DIO_ID}}",  // Change to yours
  "view": {
    "type":"home",
    "blocks": [
      {
        "type": "input",
        "block_id": "api_key_input",
        "label": {
          "type": "plain_text",
          "text": "OpenAI API Key"
        },
        "element": {
          "type": "plain_text_input",
          "action_id": "api_key",
          "placeholder": {
            "type": "plain_text",
            "text": "Enter your API key here"
          }
        }
      },
      {
        "type": "actions",
        "block_id": "submit_api_key",
        "elements": [
          {
            "type": "button",
            "text": {
              "type": "plain_text",
              "text": "Submit"
            },
            "action_id": "submit_api_key"
          }
        ]
      }
    ]
  }
}
