@baseUrl = http://localhost:8000

##### The following endpoints require an Admin Login first to any app (above)
##### One Login is enough to test all endpoints

### Health Check
POST {{baseUrl}}/gpteams
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "challenge": "OK"
}

### Prompt ChatGPT (gpt-3.5-turbo)
POST {{baseUrl}}/gpteams
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "event": {
    "text": "What is love?",
    "user": "{{$dotenv SLACK_GPTEAMS_DIO_ID}}",
    "thread_ts": "null"
  },
  "authorizations": {
    "is_bot": true
  }
}

### Danger Zone ###
##### Do not execute these endpoints unless you know what you are doing

### Set Home Page (All Users)
##### Change the "user_id" to yours (see .env file)
POST https://slack.com/api/views.publish
Authorization: Bearer {{$dotenv SLACK_GPTEAMS_DM_TOKEN}}
Content-Type: application/json

{
  "user_id": "{{$dotenv SLACK_GPTEAMS_DIO_ID}}",
  "view": {
    "type":"home",
    "blocks": [
      {
        "type": "section",
        "block_id": "welcome_section",
        "text": {
          "type": "mrkdwn",
          "text": ":wave:  *Welcome to GPTeams!*"
        }
      },
      {
        "type": "section",
        "block_id": "whitespace_1",
        "text": {
          "type": "mrkdwn",
          "text": " "
        }
      },
      {
        "type": "section",
        "block_id": "gpteams_description",
        "text": {
          "type": "mrkdwn",
          "text": "GPTeams is powered by OpenAI and ChatGPT, cutting-edge AI technologies designed to assist you in various tasks. Please note that the usage of these services is token-cost based, meaning you will need an OpenAI API Key to access them."
        }
      },
      {
        "type": "section",
        "block_id": "whitespace_2",
        "text": {
          "type": "mrkdwn",
          "text": " "
        }
      },
      {
        "type": "section",
        "block_id": "api_key_info",
        "text": {
          "type": "mrkdwn",
          "text": "If you don't have an OpenAI API Key, you can create one by visiting: <https://platform.openai.com/account/api-keys|https://platform.openai.com/account/api-keys>"
        }
      },
      {
        "type": "input",
        "block_id": "api_key_input",
        "label": {
          "type": "plain_text",
          "text": "OpenAI API Key"
        },
        "element": {
          "type": "plain_text_input",
          "action_id": "api_key",
          "placeholder": {
            "type": "plain_text",
            "text": "Enter your API key here"
          }
        }
      },
      {
        "type": "actions",
        "block_id": "submit_api_key",
        "elements": [
          {
            "type": "button",
            "text": {
              "type": "plain_text",
              "text": "Submit"
            },
            "action_id": "submit_api_key"
          }
        ]
      },
      {
        "type": "divider"
      },
      {
        "type": "context",
        "elements": [
          {
            "type": "mrkdwn",
            "text": "Developed by Tec3, LLC :computer:"
          },
          {
            "type": "mrkdwn",
            "text": "<http://www.tec3llc.com|Visit our website>"
          }
        ]
      }
    ]
  }
}
