@baseUrl = http://localhost:8000

### Login as ADMIN (Authentication)
POST {{baseUrl}}/demo/login
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "email": "{{$dotenv ADMIN_EMAIL}}",
  "password": "{{$dotenv ADMIN_PASSWORD}}"
}

##### The following endpoints require an Admin Login first (above)
##### One Login is enough to test all endpoints

### Get all messages
GET {{baseUrl}}/demo/messages
Authorization: Bearer {{$dotenv API_KEY}}

### Get message by ID
GET {{baseUrl}}/demo/messages/512dcbdb-51b8-4999-8f84-72bba82db4de
Authorization: Bearer {{$dotenv API_KEY}}

### Create message
POST {{baseUrl}}/demo/messages
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "content": "New Content",
  "user_id": "demo",
  "conversation_id": "269be190-6475-4969-a55c-c733081120de"
}

### Update message
PATCH {{baseUrl}}/demo/messages/104b8cf8-f92f-462d-acc2-ac6d9f8bf338
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "content": "New Content"
}

### Delete message
DELETE {{baseUrl}}/demo/messages/104b8cf8-f92f-462d-acc2-ac6d9f8bf338
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json