@baseUrl = http://localhost:8000

### Login as ADMIN (Authentication)
POST {{baseUrl}}/demo/login
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "email": "{{$dotenv ADMIN_EMAIL}}",
  "password": "{{$dotenv ADMIN_PASSWORD}}"
}

##### The following endpoints require an Admin Login first (above)
##### One Login is enough to test all endpoints

### Prompt GPT (text-davinci-003) - Path
POST {{baseUrl}}/gpt/What is the answer to life, the universe and everything?
Authorization: Bearer {{$dotenv API_KEY}}

### Prompt GPT (text-davinci-003) - Body
POST {{baseUrl}}/gpt
Authorization: Bearer {{$dotenv API_KEY}}

{
  "prompt": "What is the answer to life, the universe and everything?"
}

### Prompt ChatGPT (gpt-3.5-turbo) - Path
POST {{baseUrl}}/chatgpt/What is the answer to life, the universe and everything?
Authorization: Bearer {{$dotenv API_KEY}}

### Prompt ChatGPT (gpt-3.5-turbo) - Body
POST {{baseUrl}}/chatgpt
Authorization: Bearer {{$dotenv API_KEY}}

{
  "prompt": "What is the answer to life, the universe and everything?"
}

### Prompt ChatGPT-4 (gpt-4) - Path
POST {{baseUrl}}/chatgpt4/What is the answer to life, the universe and everything?
Authorization: Bearer {{$dotenv API_KEY}}

### Prompt ChatGPT-4 (gpt-4) - Body
POST {{baseUrl}}/chatgpt4
Authorization: Bearer {{$dotenv API_KEY}}

{
  "prompt": "What is the answer to life, the universe and everything?"
}

### Prompt DALL-E - Path
POST {{baseUrl}}/dalle/A Rubiks cube made of ice
Authorization: Bearer {{$dotenv API_KEY}}

### Prompt DALL-E - Body
POST {{baseUrl}}/dalle
Authorization: Bearer {{$dotenv API_KEY}}

{
  "prompt": "A Rubiks cube made of ice"
}

### Prompt Whisper - Path
POST {{baseUrl}}/whisper/https://www.example.com/file.mp3
Authorization: Bearer {{$dotenv API_KEY}}

### Prompt Whisper - Body
POST {{baseUrl}}/whisper
Authorization: Bearer {{$dotenv API_KEY}}

{
  "prompt": "example.mp3"  // Saved locally to the whisper/ folder in root
}
