@baseUrl = http://localhost:8000

### Health Check 
GET {{baseUrl}}/

### Health Check
GET {{baseUrl}}/favicon.ico

### Docs
GET {{baseUrl}}/docs

### Service: Generate random uuid
GET {{baseUrl}}/utils/uuid

### Service: Generate random hash
GET {{baseUrl}}/utils/hash

### Service: Hash input value (Param)
POST {{baseUrl}}/utils/hash/:value

### Service: Hash values (Body)
POST {{baseUrl}}/utils/hash HTTP/1.1
content-type: application/json

{
    "some_key": "some_value",
    "another_key": "another_value"
}

### Service: Generate random encryption
GET {{baseUrl}}/utils/encryption

### Service: Encrypt value (Param)
POST {{baseUrl}}/utils/encrypt/:value

### Service: Encrypt values (Body)
POST {{baseUrl}}/utils/encryption
content-type: application/json

{
    "some_key": "some_value",
    "another_key": "another_value"
}
