function reveal(req, res) {
  const {
    NODE_ENV,
    PORT,
    API_KEY,
    PROD_DB_URL,
    DEV_DB_URL,
    ADMIN_EMAIL,
    ADMIN_PASSWORD,
    SENDGRID_API_KEY,
    BACKBLAZE_APP_ID,
    BACKBLAZE_APP_KEY_ID,
    BACKBLAZE_BUCKET_ID,
    OPENAI_API_KEY,
    SLACK_GPTEAMS_DM_TOKEN,
    SLACK_GPTEAMS_BOT_ID,
    SLACK_GPTEAMS_BOT_CHANNEL,
    SLACK_GPTEAMS_ADMIN_ID,
  } = process.env;

  res.set('Content-Type', 'text/plain');
  res.send(JSON.stringify({
    NODE_ENV,
    PORT,
    API_KEY,
    PROD_DB_URL,
    DEV_DB_URL,
    ADMIN_EMAIL,
    ADMIN_PASSWORD,
    SENDGRID_API_KEY,
    BACKBLAZE_APP_ID,
    BACKBLAZE_APP_KEY_ID,
    BACKBLAZE_BUCKET_ID,
    OPENAI_API_KEY,
    SLACK_GPTEAMS_DM_TOKEN,
    SLACK_GPTEAMS_BOT_ID,
    SLACK_GPTEAMS_BOT_CHANNEL,
    SLACK_GPTEAMS_ADMIN_ID,
  }, null, 2));
}

module.exports = { reveal };
