@baseUrl = https://api.tec3devs.com

### PREP
# @name login
POST {{baseUrl}}/demo/login
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "email": "demo@tec3org.com",
  "password": "password"
}
#####


### Reset password

##### Requires Login as ADMIN first (see above)
POST {{baseUrl}}/demo/passwords/reset
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "email": "{{$dotenv ADMIN_EMAIL}}"
}

### Verify 2FA code
# Requires sending 2FA request first (code will log)
POST {{baseUrl}}/demo/passwords/verify
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "email": "{{$dotenv ADMIN_EMAIL}}",
  "code": "XXXXXX"
}
