@baseUrl = https://api.tec3devs.com

### Login as ADMIN (Authentication)
POST {{baseUrl}}/demo/login
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "email": "{{$dotenv ADMIN_EMAIL}}",
  "password": "{{$dotenv ADMIN_PASSWORD}}"
}

##### The following endpoints require an Admin Login first to any app (above)
##### One Login is enough to test all endpoints

### Prompt GPT (text-davinci-003) - Path
POST {{baseUrl}}/gpt/Generate a full paragraph of lorem ipsum text
Authorization: Bearer {{$dotenv API_KEY}}

### Prompt GPT (text-davinci-003) - Body
POST {{baseUrl}}/gpt
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "prompt": "Generate a full paragraph of lorem ipsum text"
}

### Prompt ChatGPT (gpt-3.5-turbo) - Body
POST {{baseUrl}}/chatgpt
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "prompt": "Generate a full paragraph of lorem ipsum text",
  "app_id": "groupgpt",
  "conversation_id": "bd1151f9-b562-46f2-a607-cd3aaac1c4dd"
}

### Prompt ChatGPT-4 (gpt-4) - Body
POST {{baseUrl}}/chatgpt4
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "prompt": "Generate a full paragraph of lorem ipsum text",
  "app_id": "groupgpt",
  "conversation_id": "bd1151f9-b562-46f2-a607-cd3aaac1c4dd"
}

### Prompt DALL-E - Path
POST {{baseUrl}}/dalle/A Rubiks cube made of ice
Authorization: Bearer {{$dotenv API_KEY}}

### Prompt DALL-E - Body
POST {{baseUrl}}/dalle
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "prompt": "A Rubiks cube made of ice"
}

### Prompt Whisper - Body
##### The file must be located within the whisper/ folder in root
POST {{baseUrl}}/whisper
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "file": "example.mp3"
}
