@baseUrl = https://api.tec3devs.com

### Login as ADMIN (Authentication)
POST {{baseUrl}}/demo/login
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "email": "{{$dotenv ADMIN_EMAIL}}",
  "password": "{{$dotenv ADMIN_PASSWORD}}"
}

##### The following endpoints require an Admin Login first (above)
##### One Login is enough to test all endpoints

### Prompt Enhancer (Paragraph-style) - Path
POST {{baseUrl}}/promptwiz/paragraph/Find what is the answer to life, the universe and everything
Authorization: Bearer {{$dotenv API_KEY}}

### Prompt Enhancer (Paragraph-style) - Body
POST {{baseUrl}}/promptwiz/paragraph
Authorization: Bearer {{$dotenv API_KEY}}

{
  "prompt": "What is the answer to life, the universe and everything?"
}

### Prompt Enhancer (Structured-style) - Path
POST {{baseUrl}}/promptwiz/structured/Find what is the answer to life, the universe and everything
Authorization: Bearer {{$dotenv API_KEY}}

### Prompt Enhancer (Structured-style) - Body
POST {{baseUrl}}/promptwiz/structured
Authorization: Bearer {{$dotenv API_KEY}}

{
  "prompt": "What is the answer to life, the universe and everything?"
}
