@baseUrl = https://api.tec3devs.com

### Login as USER (Authentication)
# @name login
POST {{baseUrl}}/demo/login
Authorization: Bearer {{$dotenv API_KEY}}
Content-Type: application/json

{
  "email": "demo@tec3org.com",
  "password": "password"
}

### Token definition
@token = {{login.response.body.accessToken.$}}
#####


##### The following endpoints require Login first (above)


### Find user
GET {{baseUrl}}/demo/users/demo
Authorization: Bearer {{token}}

### Edit user
PATCH {{baseUrl}}/demo/users/demo
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "masterchiefsensei"
}

### Delete user
##### Will require re-seeding to get the user back
DELETE {{baseUrl}}/demo/users/demo
Authorization: Bearer {{token}}

### Logout
POST {{baseUrl}}/demo/logout
Authorization: Bearer {{token}}
